spring:
  profiles:
    default: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:postgresql://<IP>"
    username: postgres
    password: 
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:postgresql://<IP>"
    username: postgres
    password: 
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
